openapi: "3.0.0"
info:
  description: Mock API Definition
  version: 1.0.0
  title: Widget API
  
servers:
  - url: https://johnsauthdemo.irisws-development.co.uk/api/v1

paths:
  /widgets:
    get:
      summary: Get all Widgets
      responses:
        200:
          description: Valid response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Widgets'
        401:
          description: Not Authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'            
        4XX:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'          
        5XX:
          description: Server-side error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'          
      security:
      - OAuth2: []
    post:
      summary: Create a new Widget
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewWidget'
      responses:
        200:
          description: Successful creation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Widget'   
        401:
          description: Not Authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'            
        4XX:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'          
        5XX:
          description: Server-side error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'                  
      security:
      - OAuth2: []                
    delete:
      summary: Delete all Widgets
      responses:
        200:
          description: Successful delete
        401:
          description: Not Authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'            
        4XX:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'          
        5XX:
          description: Server-side error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'            
      security:
      - OAuth2: []    
      
  /widgets/{widgetId}:
    get:
      summary: Get a specfic Widget
      parameters: 
        - in: path
          name: widgetId
          schema:
            type: integer
          required: true
          description: Unique identifier of the Widget
          example: 1
      responses:
        200:
          description: Valid response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Widget'      
        401:
          description: Not Authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'  
        404:
          description: Widget not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error' 
        4XX:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'          
        5XX:
          description: Server-side error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'                  
      security:
        - OAuth2: [] 
    put:
      summary: Update a specfic Widget
      parameters: 
        - in: path
          name: widgetId
          schema:
            type: integer
          required: true
          description: Unique identifier of the Widget
          example: 1          
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewWidget'                
      responses:
        200:
          description: Successful update
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Widget'  
        401:
          description: Not Authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'  
        404:
          description: Widget not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error' 
        4XX:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'          
        5XX:
          description: Server-side error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'                  
      security:
        - OAuth2: [] 
    delete:
      summary: Delete a specfic Widget
      parameters: 
        - in: path
          name: widgetId
          schema:
            type: integer
          required: true
          description: Unique identifier of the Widget
          example: 1          
      responses:
        200:
          description: Successful deletion
        401:
          description: Not Authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'  
        404:
          description: Widget not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error' 
        4XX:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'          
        5XX:
          description: Server-side error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'            
      security:
        - OAuth2: []         

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://hcm-hub-rnd.auth.eu-west-1.amazoncognito.com/oauth2/authorize
          scopes: {}
    
  schemas:
    Widgets:
      type: array
      items: 
        $ref: '#/components/schemas/Widget'
    
    NewWidget:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: foo
        type:
          type: string
          example: Standard
      
    Widget:
      allOf:
        - $ref: '#/components/schemas/NewWidget'
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          example: 1
          
    Error:
      type: object
      properties:
        code:
          type: string
          example: 400-02-112
        description:
          type: string
          example: Widget ID is not in the correct format

